# Generated by Django 6.0.1 on 2026-01-23 01:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id_equipo', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_inventario', models.CharField(max_length=50, unique=True)),
                ('tipo', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('numero_serie', models.CharField(max_length=100, unique=True)),
                ('anio_adquisicion', models.IntegerField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('OPERATIVO', 'Operativo'), ('MANTENIMIENTO', 'En Mantenimiento'), ('DAÑADO', 'Dañado'), ('BAJA', 'Dado de Baja'), ('PRESTAMO', 'En Préstamo')], max_length=20)),
                ('condicion_fisica', models.CharField(choices=[('EXCELENTE', 'Excelente'), ('BUENO', 'Bueno'), ('REGULAR', 'Regular'), ('MALO', 'Malo')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id_mantenimiento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('PREVENTIVO', 'Preventivo'), ('CORRECTIVO', 'Correctivo'), ('PREDICTIVO', 'Predictivo'), ('CALIBRACION', 'Calibración')], max_length=20)),
                ('descripcion', models.TextField()),
                ('actividades_realizadas', models.TextField()),
                ('repuestos', models.TextField(blank=True)),
                ('costo_mantenimiento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado_posterior', models.CharField(max_length=50)),
                ('observaciones', models.TextField(blank=True)),
                ('proximo_mantenimiento', models.DateField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.equipo')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id_ubicacion', models.AutoField(primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=100)),
                ('aula_laboratorio', models.CharField(max_length=100)),
                ('piso', models.CharField(blank=True, max_length=20)),
                ('edificio', models.CharField(blank=True, max_length=50)),
                ('capacidad', models.IntegerField(default=0)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'unique_together': {('area', 'aula_laboratorio')},
            },
        ),
        migrations.CreateModel(
            name='AsignacionEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True)),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('equipo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventario.equipo')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.ubicacion')),
            ],
        ),
    ]
