# Generated by Django 5.1 on 2026-01-23 03:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignacionequipo',
            options={'verbose_name': 'Asignación de Equipo', 'verbose_name_plural': 'Asignaciones de Equipos'},
        ),
        migrations.AlterModelOptions(
            name='equipo',
            options={'ordering': ['codigo_inventario'], 'verbose_name': 'Equipo', 'verbose_name_plural': 'Equipos'},
        ),
        migrations.AlterModelOptions(
            name='mantenimiento',
            options={'ordering': ['-fecha'], 'verbose_name': 'Mantenimiento', 'verbose_name_plural': 'Mantenimientos'},
        ),
        migrations.AlterModelOptions(
            name='ubicacion',
            options={'ordering': ['area', 'aula_laboratorio'], 'verbose_name': 'Ubicación', 'verbose_name_plural': 'Ubicaciones'},
        ),
        migrations.AlterUniqueTogether(
            name='ubicacion',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='asignacionequipo',
            name='equipo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventario.equipo', verbose_name='Equipo'),
        ),
        migrations.AlterField(
            model_name='asignacionequipo',
            name='fecha_asignacion',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de Asignación'),
        ),
        migrations.AlterField(
            model_name='asignacionequipo',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='asignacionequipo',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.AlterField(
            model_name='asignacionequipo',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.ubicacion', verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='anio_adquisicion',
            field=models.IntegerField(verbose_name='Año de Adquisición'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='codigo_inventario',
            field=models.CharField(max_length=50, unique=True, verbose_name='Código de Inventario'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='condicion_fisica',
            field=models.CharField(choices=[('EXCELENTE', 'Excelente'), ('BUENO', 'Bueno'), ('REGULAR', 'Regular'), ('MALO', 'Malo')], max_length=20, verbose_name='Condición Física'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='costo',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='estado',
            field=models.CharField(choices=[('OPERATIVO', 'Operativo'), ('MANTENIMIENTO', 'En Mantenimiento'), ('DAÑADO', 'Dañado'), ('BAJA', 'Dado de Baja')], max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='marca',
            field=models.CharField(max_length=100, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='modelo',
            field=models.CharField(max_length=100, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='numero_serie',
            field=models.CharField(max_length=100, unique=True, verbose_name='Número de Serie'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='tipo',
            field=models.CharField(choices=[('COMPUTADORA', 'Computadora'), ('LAPTOP', 'Laptop'), ('IMPRESORA', 'Impresora'), ('PROYECTOR', 'Proyector'), ('TABLET', 'Tablet'), ('SERVER', 'Servidor'), ('SWITCH', 'Switch'), ('ROUTER', 'Router'), ('MONITOR', 'Monitor'), ('TELEVISOR', 'Televisor')], max_length=50, verbose_name='Tipo de Equipo'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='actividades_realizadas',
            field=models.TextField(verbose_name='Actividades Realizadas'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='costo_mantenimiento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo de Mantenimiento'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.equipo', verbose_name='Equipo'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='estado_posterior',
            field=models.CharField(max_length=50, verbose_name='Estado Posterior'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='fecha',
            field=models.DateField(verbose_name='Fecha de Mantenimiento'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='proximo_mantenimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Próximo Mantenimiento'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='repuestos',
            field=models.TextField(blank=True, null=True, verbose_name='Repuestos Utilizados'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='tipo',
            field=models.CharField(choices=[('PREVENTIVO', 'Preventivo'), ('CORRECTIVO', 'Correctivo'), ('PREDICTIVO', 'Predictivo'), ('CALIBRACION', 'Calibración')], max_length=20, verbose_name='Tipo de Mantenimiento'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='area',
            field=models.CharField(max_length=100, verbose_name='Área'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='aula_laboratorio',
            field=models.CharField(max_length=100, verbose_name='Aula/Laboratorio'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='edificio',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Edificio'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='piso',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Piso'),
        ),
        migrations.RemoveField(
            model_name='ubicacion',
            name='capacidad',
        ),
    ]
