# Generated by Django 5.2.8 on 2026-01-27 23:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id_asignatura', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('creditos', models.IntegerField()),
                ('horas_semana', models.IntegerField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Asignatura',
                'verbose_name_plural': 'Asignaturas',
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id_estudiante', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
            },
        ),
        migrations.CreateModel(
            name='PeriodoAcademico',
            fields=[
                ('id_periodo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Período Académico',
                'verbose_name_plural': 'Períodos Académicos',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionEvaluacion',
            fields=[
                ('id_config', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_evaluacion', models.CharField(max_length=100)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calificaciones.asignatura')),
            ],
            options={
                'verbose_name': 'Configuración de Evaluación',
                'verbose_name_plural': 'Configuraciones de Evaluación',
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id_docente', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('especialidad', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('seccion', models.CharField(max_length=10)),
                ('cupo_maximo', models.IntegerField(default=30)),
                ('cupo_actual', models.IntegerField(default=0)),
                ('horario', models.CharField(blank=True, max_length=100, null=True)),
                ('aula', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calificaciones.asignatura')),
                ('docente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calificaciones.docente')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calificaciones.periodoacademico')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'unique_together': {('asignatura', 'periodo', 'seccion')},
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id_matricula', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_matricula', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('matriculado', 'Matriculado'), ('aprobado', 'Aprobado'), ('reprobado', 'Reprobado'), ('incompleto', 'Incompleto')], default='matriculado', max_length=20)),
                ('nota_final', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calificaciones.curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calificaciones.estudiante')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
                'unique_together': {('estudiante', 'curso')},
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id_calificacion', models.AutoField(primary_key=True, serialize=False)),
                ('nota', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('configuracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calificaciones.configuracionevaluacion')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calificaciones.matricula')),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
                'unique_together': {('matricula', 'configuracion')},
            },
        ),
    ]
