# Generated by Django 5.2.8 on 2026-01-28 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignatura',
            name='creditos',
        ),
    ]
